trigger:
  batch: 'true'
  branches:
    include:
    - main
  paths:
    exclude:
    - '*README.md'
    - 'docs/*'

parameters:
  - name: 'vmImage'
    type: string
    default: 'windows-2022'
    values:
    - windows-latest
    - windows-2022

pool:
  vmImage: parameters.vmImage

variables:
  LGTM.UploadSnapshot: true
  solution: '**/*.sln'
  msbuildPath: '"%ProgramFiles(x86)%\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"'
  BuildPlatform: x64
  BuildConfiguration: Release

jobs:
  - job: SDLCompliance
    displayName: 'Running SDL Compliance Policy checks'
    continueOnError: true
    steps:    
    # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/advanced-security-codeql-init-v1?view=azure-pipelines#remarks
    - task: AdvancedSecurity-Codeql-Init@1
      displayName: "Initialize CodeQL"
      inputs:
        languages: 'cpp'
        querysuite: 'code-scanning'
        sourcesfolder: '$(Build.SourcesDirectory)\LogMonitor'
        buildtype: Manual
        ram: 8192

    # # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/msbuild-v1?view=azure-pipelines#should-i-use-the-visual-studio-build-task-or-the-msbuild-task
    # - task: MSBuild@1
    #   displayName: Build LogMonitor project
    #   inputs:
    #     # msbuildLocationMethod: 'location'
    #     # msbuildLocation: '$(msbuildPath)'
    #     solution: '$(BUILD.SourcesDirectory)\$(solution)'
    #     msbuildArchitecture: 'x64'
    #     platform: '$(BuildPlatform)'
    #     configuration: '$(BuildConfiguration)'
    #     clean: true
    #     createLogFile: true
    #     logFileVerbosity: 'diagnostic'
        
    # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/msbuild-v1?view=azure-pipelines#should-i-use-the-visual-studio-build-task-or-the-msbuild-task
    - task: VSBuild@1
      displayName: Build LogMonitor project
      inputs:
        solution: '$(BUILD.SourcesDirectory)\$(solution)'
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'
        clean: true
        createLogFile: true
        logFileVerbosity: 'diagnostic'    
      
    - task: AdvancedSecurity-Codeql-Analyze@1
      displayName: "Perform CodeQL Analysis"

    - task: PublishSecurityAnalysisLogs@3
      displayName: 'Publish Security Analysis Logs'
      continueOnError: true
      inputs:
        ArtifactName: 'CodeAnalysisLogs'
        ArtifactType: 'Container'
        PublishProcessedResults: false
        AllTools: false
        Semmle: true
        ToolLogsNotFoundAction: 'Standard'
